### ISSUE TITLE
Meta access

### ISSUE THREAD

**Issue by jessejanderson** [geolessel/pco-dashboard#13]
Currently, the component store only updates data with the `data` key of the api result, it would be great to be able to access the `meta` data for things like a `total_count` value so that we can have a component that shows a total count without having to page through lots of extra data to count.

![image](https://user-images.githubusercontent.com/8367129/80858899-8744ff00-8c11-11ea-9e10-015429817908.png)

**Comment by geolessel** [comment]
Added in #16
